config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'students#index'
  
  resources :students do
   get '/entries/ids', :to => 'entries#get_ids'
   resources :entries, except: [:index]
   get '/entries/:id/entry_data', :to => 'entries#entry_data'
  end
  
  resources :rehearsals
  
  resources :events do
    resources :rehearsals, only: [:index]
  end
  
  resources :comments, only: [:create]
  
  get '*a', :to => 'errors#routing'
end

app/models/rehearsal.rb
class Rehearsal < ApplicationRecord
  belongs_to :event
  has_many :attendances, dependent: :destroy
  has_many :students, through: :attendances
  
  delegate :user, :to => :event, :allow_nil => true
  
  validates :venue, presence: true
  
  def students_attending
    self.attendances.going.collect do |attendance|
      Student.find(attendance.student_id)
    end
  end
  
  def count_attending
    self.students_attending.count
  end
  
  def students_attended
    self.attendances.went.collect do |attendance|
      Student.find(attendance.student_id)
    end
  end
  
  def count_attended
    self.students_went.count
  end
end

app/controllers/rehearsals_controller.rb
class RehearsalsController < ApplicationController
  before_action :set_rehearsal, only: [:show, :edit, :update, :destroy]
  
  def index
    if params[:event_id]
      @event = current_user.events.find(params[:event_id])
      @rehearsals = @event.rehearsals
    else
      @rehearsals = current_user.rehearsals
      @students = current_user.students
    end
    
    respond_to do |format|
      format.html
      format.json { render :json => @rehearsals }
    end
  end
  
  def new
    @events = current_user.events 
    @rehearsal = current_user.rehearsals.build
  end
  
  def create
    event = current_user.events.find(rehearsal_params[:event_id])
    @rehearsal = event.rehearsals.build(rehearsal_params)
    if @rehearsal.save
      redirect_to rehearsals_path, notice: "Added new rehearsal for #{event.name}."
    else
      render :new
    end
  end
  
  def show
    @students = current_user.students
  end
  
  def edit
  end 
  
  def update
    student_id = rehearsal_params[:student_id]
    attending = rehearsal_params[:going]
    attended = rehearsal_params[:went]
    
    if student_id
      attendance = Attendance.find_or_create_by(rehearsal_id: @rehearsal.id, student_id: student_id)
      case 
      when !attending.nil?
        attendance = attendance.update(going: attending)
        redirect_to rehearsal_path(@rehearsal)
      when !attended.nil?
        attendance = attendance.update(went: attended)
        redirect_to rehearsal_path(@rehearsal)
      end
    else
      @rehearsal.update(rehearsal_params)
      redirect_to rehearsal_path(@rehearsal), notice: "Rehearsal for #{@rehearsal.event.name} was successfully updated."
    end
  end
  
  def destroy
    @rehearsal.destroy
    redirect_to rehearsals_path, notice: "Rehearsal for #{@rehearsal.event.name} was destroyed."
  end
  
  private
  
  def set_rehearsal
    begin 
      @rehearsal = current_user.rehearsals.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @rehearsal = nil
      redirect_to rehearsals_path, notice: "Rehearsal record not found."
    else
      @rehearsal = current_user.rehearsals.find(params[:id])
    end
  end
  
  def rehearsal_params
    params.require(:rehearsal).permit(:event_id, :venue, :time, :student_id, :going, :went)
  end
end

app/views/rehearsals/_form.html.erb
<%= render "shared/error_messages", :target => rehearsal %>

<div class="card w-75 mx-auto">
  <div class="card-body">
    <%= form_for @rehearsal do |f| %>
      <div class="form-group row">
      <%= f.label "Rehearsal for" %>
      <%= f.collection_select :event_id, @events, :id, :name, :with_css_classes => "form-control" %>
      </div>
      <div class="form-group row col-md-8">
      <%= f.label :venue %>
      <%= f.text_field :venue, class: "form-control" %>
      </div>
      <div class="form-group row col-md-8">
      <%= f.label :time %>
      <%= f.datetime_select(:time, default: Date.today, ampm: true, class: "form-control" ) %>
      </div>
      <%= link_to "Cancel", rehearsals_path, class: "btn btn-sm btn-secondary" %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/rehearsals/_going_to_rehearsal.html.erb
<%= form_for @rehearsal, method: :patch do |f| %>
  <%= f.hidden_field :student_id, value: student_id %>
  <%= f.hidden_field :going, value: going %>
  <%= f.submit button_text %>
<% end %>

app/views/rehearsals/_rehearsal.html.erb
<tr>
  <td>
    <%= rehearsal.time.strftime("%B %-d, %Y") %> at <%= rehearsal.time.strftime("%k:%M")%>
  </td>
  <td>
    <%= link_to rehearsal.event.name, rehearsal_path(rehearsal) %>
  </td>
  <td>
    <%= rehearsal.venue %>
  </td>
</tr>

app/views/rehearsals/_went_to_rehearsal.html.erb
<%= form_for @rehearsal, method: :patch do |f| %>
  <%= f.hidden_field :student_id, value: student_id %>
  <%= f.hidden_field :went, value: went %>
  <%= f.submit button_text %>
<% end %>

app/views/rehearsals/edit.html.erb
<%= render partial:"form", locals: { rehearsal: @rehearsal } %>

app/views/rehearsals/index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"><strong>Time</strong></th>  
      <th scope="col"><strong>Rehearsal</strong></th>  
      <th scope="col"><strong>Venue</strong></th>
      <th scope="col">
        <strong>
          <%= link_to "Add Rehearsal", new_rehearsal_path, class: "btn btn-sm btn-primary" %>
        </strong>
      </th> 
    </tr>
  </thead>
  <% @rehearsals.each do |rehearsal| %>
  <tr>
    <td><%= rehearsal.time.strftime("%B %-d, %Y") %> at <%= rehearsal.time.strftime("%k:%M")%></td>
    <td><%= link_to rehearsal.event.name, rehearsal_path(rehearsal) %></td>
    <td><%= rehearsal.venue %></td>
    <td>
    <%= form_for rehearsal, method: :delete do |f| %>
      <%= f.submit "Delete" %>
    <% end %>
    </td>
  </tr>
  <% end %>
</table>

app/views/rehearsals/new.html.erb
<%= render partial:"form", locals:  {rehearsal: @rehearsal } %>

app/views/rehearsals/show.html.erb
<div class="card w-50 mx-auto">
  <div class="card-body">
    <h5 class="card-title">Rehearsal for <%= @rehearsal.event.name %></h5>
    <p class="card-text"><%= @rehearsal.time.strftime("%B %-d, %Y") %> at <%= @rehearsal.time.strftime("%k:%M")%></p>
    <p class="card-text"><%= @rehearsal.venue %></p>
    <%= link_to "Back", rehearsals_path(@rehearsal), class: "btn btn-sm btn-secondary" %>
    <%= link_to "Edit", edit_rehearsal_path(@rehearsal), class: "btn btn-sm btn-primary" %>
    <br></br>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col"><strong>Student Name</strong></th>  
          <th scope="col"><strong>Attending</strong></th>
          <!--<th scope="col"><strong>Attended</strong></th>-->
        </tr>
      </thead>
      <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.name, student_path(student) %></td>
        <td>
        <!--Toggle value of 'going' boolean-->
        <% if @rehearsal.students_attending.include?(student) %>
          <%= render partial: "going_to_rehearsal", locals: { student_id: student.id, going: false, button_text: "Yes"} %>
        <% else %>
          <%= render partial: "going_to_rehearsal", locals: { student_id: student.id, going: true, button_text: "No" } %>
        <% end %>
        </td>
        <td>
        <!--Toggle value of 'went' boolean-->
        <%# if @rehearsal.students_attended.include?(student) %>
          <%#= render partial: "went_to_rehearsal", locals: { student_id: student.id, went: false, button_text: "Yes"} %>
        <%# else %>
          <%#= render partial: "went_to_rehearsal", locals: { student_id: student.id, went: true, button_text: "No"} %>
        <%# end %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>