config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'students#index'
  
  resources :students do
   get '/entries/ids', :to => 'entries#get_ids'
   resources :entries, except: [:index]
   get '/entries/:id/entry_data', :to => 'entries#entry_data'
  end
  
  resources :rehearsals
  
  resources :events do
    resources :rehearsals, only: [:index]
  end
  
  resources :comments, only: [:create]
  
  get '*a', :to => 'errors#routing'
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_many :entries, dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :rehearsals, through: :attendances
  
  validates :name, presence: true
  validates :email, 
            :presence => true, 
            :uniqueness => true, 
            :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
            
  def rehearsals_attending
    self.attendances.going.collect do |attendance|
      Rehearsal.find(attendance.rehearsal_id)
    end
  end
  
  def count_rehearsals
    self.rehearsals_attending.count
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  
  def index
    @students = current_user.students
  end
  
  def show
    @entry = current_user.students.find(params[:id]).entries.build
  end
  
  def new
    @student = current_user.students.build
  end
  
  def create
    @student = current_user.students.build(student_params)
    if @student.save 
      redirect_to student_path(@student)
    else
      render :new
    end
  end
  
  def edit
    @student = current_user.students.find(params[:id])
  end
  
  def update
    if @student.update(student_params)
      redirect_to student_path(@student), notice: 'Student record was successfully updated.'
    else
      render :edit
    end
  end
  
  def destroy
    @student.destroy
  end
  
  private
  
  def set_student
    begin
      @student = current_user.students.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @student = nil
      redirect_to students_path, notice: "Student record not found."
    else
      @student = current_user.students.find(params[:id])
    end
  end
  
  def student_params
    params.require(:student).permit(:name, :email)
  end
end

app/views/students/_form.html.erb
<%= render "shared/error_messages", :target => student %>

<%= form_for student do |f| %>
<div class="form-group row col-md-6">
  <strong><%= f.label :name %></strong>
  <%= f.text_field :name, class: "form-control" %>
</div>
<div class="form-group row col-md-6">
  <strong><%= f.label :email %></strong>
  <%= f.email_field :email, class: "form-control" %>
</div>
  <%= link_to "Cancel", students_path, class: "btn btn-sm btn-secondary" %>
  <%= f.submit %>
<% end %>

app/views/students/_student.html.erb
<tr class="student-record" data-id="<%= student.id %>">
  <td><%= student.name %></td>
  <td><%= student.email %></td>
  <td><%= link_to "View", student_path(student) %></td>
  <td><%= link_to "Edit", edit_student_path(student) %></td>
  <td>
  <%= form_for student, method: :delete do |f| %>
      <%= f.submit "Delete" %>
  <% end %>
  </td>
</tr>

app/views/students/edit.html.erb
<fieldset>
<legend><h2>Update Student Info</h2></legend>
<%= render partial: "form", locals: {student: @student} %>
</fieldset>

app/views/students/index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"><strong>Name</strong></th>
      <th scope="col"><strong>Email</strong></th>
      <th scope="col"><strong>Details</strong></th>
      <th scope="col"></th>
      <th scope="col">
        <strong>
        <%= link_to "Add Student", new_student_path, class: "btn btn-sm btn-primary" %>
        </strong>
      </th>
    </tr>
  </thead>
  <tbody>
    <%= render(:partial => 'student', :collection => @students) || 'No records' %>
  </tbody>
</table>

app/views/students/new.html.erb
<fieldset>
<legend><h2>New Student</h2></legend>
<%= render partial: "form", locals: {student: @student} %>
</fieldset>

app/views/students/show.html.erb
<fieldset>
<legend><h2>Student Info</h2></legend>
  <table>
    <tr>
      <td><strong>Name</strong></td>
      <td><%= @student.name %></td>
    </tr>
    <tr>
      <td><strong>Email</strong></td>
      <td><%= @student.email %></td>
    </tr>
  </table>
</fieldset>
<strong>
  <%= link_to "Back", students_path, class: "btn btn-sm btn-secondary" %>
</strong>

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#entries" role="tab" aria-controls="home" aria-selected="true">Entries</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#rehearsals" role="tab" aria-controls="profile" aria-selected="false">Rehearsals</a>
  </li>
</ul>

<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="entries" role="tabpanel" aria-labelledby="entries-tab">
   <ul class="list-group list-group-flush">
      <li class="list-group-item">
       <%= link_to "Add New Entry", new_student_entry_path(@student, @entry), class: "btn btn-sm btn-primary" %>
      </li>
      <%= render @student.entries %>
    </ul> 
  </div>
  
  <div class="tab-pane fade" id="rehearsals" role="tabpanel" aria-labelledby="rehearsals-tab">
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><%= link_to "Add New Rehearsal", rehearsals_path, class: "btn btn-sm btn-primary" %></li>
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col"><strong>Time</strong></th>  
            <th scope="col"><strong>Rehearsal</strong></th>  
            <th scope="col"><strong>Venue</strong></th>
          </tr>
        </thead>
        <%= render @student.rehearsals_attending %>
      </table>
    </ul> 
  </div>
</div>