config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'students#index'
  
  resources :students do
   get '/entries/ids', :to => 'entries#get_ids'
   resources :entries, except: [:index]
   get '/entries/:id/entry_data', :to => 'entries#entry_data'
  end
  
  resources :rehearsals
  
  resources :events do
    resources :rehearsals, only: [:index]
  end
  
  resources :comments, only: [:create]
  
  get '*a', :to => 'errors#routing'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :rehearsals, dependent: :destroy
  
  validates :name, :venue, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  
  def index
    @events = current_user.events
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save 
      redirect_to event_path(@event), notice: "Event was successfully created."
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @event.update(event_params)
    if @event.save
      redirect_to events_path, notice: "Event was successfully upddated."
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: "#{@event.name} record was destroyed."
  end
  
  private
  def set_event
    begin
      @event = current_user.events.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @event = nil
      redirect_to events_path, notice: "Event record not found"
    else
      @event = current_user.events.find(params[:id])
    end
  end
  
  def event_params
    params.require(:event).permit(:name, :time, :venue)
  end
end

app/views/events/_event.html.erb
<tr>
 <td><%= event.time.strftime("%B %-d, %Y") %> at <%= event.time.strftime("%k:%M")%></td>
 <td><%= link_to event.name, event_path(event) %></td>
 <td><%= event.venue %></td>
 <td><%= event.rehearsals.count %></td>
 <td>
 <%= form_for event, method: :delete do |f| %>
   <%= f.submit "Delete" %>
 <% end %>
 </td>
</tr>
 

app/views/events/_form.html.erb
<%= render "shared/error_messages", :target => event %>

<div class="card w-75 mx-auto">
  <div class="card-body">
    <%= form_for @event do |f| %>
      <div class="form-group row col-md-8">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control col-md-6"  %>
      </div>
      <div class="form-group row col-md-8">
      <%= f.label :venue %>
      <%= f.text_field :venue, class: "form-control col-md-6" %>
      </div>
      <div class="form-group row col-md-8">
      <%= f.label :time %>
      <%= f.datetime_select(:time, default: Date.today, ampm: true, class: "form-control" ) %>
      </div>
      <%= link_to "Cancel", events_path, class: "btn btn-sm btn-secondary" %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<%= render partial: "form", locals: { event: @event } %>

app/views/events/index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"><strong>Time</strong></th>  
      <th scope="col"><strong>Name</strong></th>  
      <th scope="col"><strong>Venue</strong></th>
      <th scope="col"><strong>Rehearsals</strong></th>
      <th scope="col">
        <strong>
          <%= link_to "Add Event", new_event_path, class: "btn btn-sm btn-primary" %>
        </strong>
      </th> 
    </tr>
  </thead>
  <%= render @events %>
</table>

app/views/events/new.html.erb
<%= render partial: "form", locals: { event: @event } %>

app/views/events/show.html.erb
<%= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track': 'reload' %>
<div class="card w-50 mx-auto">
  <div class="card-body">
    <h5 class="card-title"><%= @event.name %></h5>
    <p class="card-text"><%= @event.time.strftime("%B %-d, %Y") %> at <%= @event.time.strftime("%k:%M")%></p>
    <p class="card-text"><%= @event.venue %></p>
    <%= link_to "Back", events_path(@event), class: "btn btn-sm btn-secondary" %>
    <%= link_to "Edit", edit_event_path(@event), class: "btn btn-sm btn-primary" %>
  </div>
</div>

<%= link_to "Load Rehearsals", event_rehearsals_path(@event, :json), id: "load_rehearsals" %>
<table id="rehearsals" class="table table-hover">
  <tbody></tbody>
</table>