config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'students#index'
  
  resources :students do
   get '/entries/ids', :to => 'entries#get_ids'
   resources :entries, except: [:index]
   get '/entries/:id/entry_data', :to => 'entries#entry_data'
  end
  
  resources :rehearsals
  
  resources :events do
    resources :rehearsals, only: [:index]
  end
  
  resources :comments, only: [:create]
  
  get '*a', :to => 'errors#routing'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teaching Notes</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Poller+One|Raleway:500" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <div class="container">
    <header>
      <nav class="navbar navbar-fixed-top navbar-dark bg-primary">
        <%= link_to "Teaching Notes", root_url, :class => 'navbar-brand logo' %>
        <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% end %>
        </p>
      </nav>
    </header>
    <% if user_signed_in? %>
    <ul class="nav nav-pills justify-content-center">
      <li class="nav-item">
        <%= link_to "Students", students_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Rehearsals", rehearsals_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Events", events_path, class: "nav-link" %>
      </li>
    </ul>
    <% end %>
    
    <%= content_tag(:div, flash[:error], id: "flash_error", class: "alert alert-danger", role: "alert") if flash[:error] %>
    <%= content_tag(:div, flash[:notice], id: "flash_notice", class: "alert alert-success", role: "alert" ) if flash[:notice] %>
    <%= content_tag(:div, flash[:alert], id: "flash_alert", class: "alert alert-info", role: "alert") if flash[:alert] %>
    <%= yield %>
    </div>
  </body>
</html>